spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost/firstdb
    username: root
    password: '1243'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+3
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true

server:
  port: 8080
